export const CERTIFICACAO_PAGE_SELECTORS = {
  path: "/certificacao",
  homeCard: "#ipeqef",
  subscribeForm: "#rbFormEtapa1",
  subscribeName: "[name='pessoa.nome']",
  subscribeEmail: "[name='pessoa.emailPrincipal']",
  subscribePhoneCountry: ".iti__selected-country",
  subscribePhoneNumber: "[name='pessoa.telefonePrincipal']",
  subscribeSubmitButton: "#rbBtnNext",
  validationMessage: "[name='validationMessage']",
  facebookLink: "#io0o4o",
  instagramLink: "#il7i3x",
  linkedinLink: "#i2m2tn",
  youtubeLink: "#ifpwp7",
};
